project:
  type: website

website:
  title: "Javier Enrique Aguilar"
  description: "Postdoctoral Researcher in Bayesian Statistics | Bayesian computation, priors, probabilistic programming"
  # ... el resto de la configuración
